version: 0.2

phases:
  install:
    runtime-versions:
      # If using Amazon Linux 2 standard image, install Terraform manually
      docker: 18
    commands:
      - echo Installing Terraform...
      - curl -O https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws sts get-caller-identity
      - echo Initializing Terraform...
      - terraform init

  build:
    commands:
      - echo Validating Terraform code...
      - terraform validate
      - echo Planning Terraform deployment...
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform plan...
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
